travis:
  secure:
    BINSTAR_TOKEN: A4BYvey7KcWOhaN1F2gQ7ArRN2UXp4AnuNsY2ER+tmMPREgOcsoS61Zz2DnKxUwVNJmRioy/c6pXNEB9pQvAt0hi9l+/LThEqMWz+Xr/Cw4JpdyV1efOARXFLXchv4bgTBNSnEeRAXqiGMZIFxdTKbtIxyeR72L4hgqkmhkzb3gv/jU/SNVriFPkaTnWx7ZivNRaH5N4xu0jZHLXckTpwGOH0xt8ebJktcSz0+ny8Yi3LUqoFJUG6y/Acxcz+LtN5d+TaOpK0Y4oTK4xK7YaZej1nibw7h5fhBOpakNKEAS/99ObCoJNLeT5dTO2bbTpFzuLh2MCeoj7jAoPs+Dk5TQm6Pf47b1vMc0eJH1WZBzOQMihnG/Nc9URMiWvg/m87tLKgqF5bz9kRBDyt5KbWUkBWjhhqT307LpcyoSZOUI5zj2KgpJEyxv32sRT7lCbjBRW+fgkPKpnCtOC0oxc2WHl9w9k4K37QH1EqDnGP98dgIn6WXCL5O/xHF+ilpjm3IF2XkviAGVfXG/VyzzxHbwxdVgIFBkByOj7uv+t3Tdo/u3fw0zEh63kwKo3iS/diuHSdmRPWL2HV67Dhy3oPcUn0Yn2nbf4yQP8T8pFLKTjFAOr3M/xjqi1tHCSvc5aVyZ6q9ePgs+lbW7pYVqNtPPow4Nn3mcZPmLYTKHnYP0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
