travis:
  secure:
    BINSTAR_TOKEN: Qd7v1JGynIoasUZ2s33FWGwaR0F3cciLEwC0U1IC+Vx1cYZFeQK5pdSySwLUuL6ERGPkKu2jNqSlC/LobjN6a2uT2EmEyPJnZqw6RQds92+mmbwQDN9ePf/PEqW07X8h8ut5cMT0eSTLxWY+douLrBObCGI2uzgtmG+KI7dLB4o5/C+CE1hFqPXcUxA7ciTrFM1ZdR843xYytJTMgFWXfX0vCKRoe99Qsz9P2mcRI6K/zY0BpAJhQGgdodfDAXFWp/Vudkm3q+fjYDKt5ZHkGharIUM+ozQLvXUOkgOi4qItn0TkPmhjyox/SZDjgjbVVNqh6AyxKIfmpcs4M5kn3uAtN6iaQ+S55jQ9p/Vsuj+iiy8ayJXbJzLmNjGSeaaJEyc8/31+nsrA450ptI5ecVjjfbb76JTJojZ5MscrqsBG2+epRqVdtFfVS69segJOnUQUPg8s+pEqYfZf/lti74MRztFae7Cm/oCCZ+oOTCuxa5FmMbUkgpDRaQEiYBYaQUjpgc1RxMaGq/cI/1whEwhhBI/Bd0+cwIqEfANOFTMT5SL6F79AC0XJjuJtkaMDpK/TDrlV8Pfl4C8TpaW6hJzSpjsX6OBc+n/X3DhJdZWrRcK3dFvUHBGiC1Ua5eGwakzrWFW1uDj2OH/kP2pwmvKdNrYEJglfJPi2lxoObnw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
